# Site
repository: kartikeyavi/modern-resume-theme
favicon: images/favicon.ico


# Content configuration version
version: 2

# Personal info
name:  KARTIKEYA SINGH
title: Machine Learning Developer
email: kartikeyavia2r@gmail.com  
phone: +91-7339910494

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  kartikeyavi
linkedin_username: kartikeyavi


# About Section
# about_title: About Me
about_profile_image: images/Profile Picture.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a passionate Machine Learning Engineer with a strong foundation in data science and a knack for building efficient and accurate models. I leverage my expertise in Python, R, TensorFlow, and other state-of-the-art libraries to tackle complex challenges across various domains
  My journey began with a deep theoretical understanding of core concepts like Advanced ML, Computer Vision, Natural Language Processing, and Probability & Linear Algebra.  I further honed my skills through practical experience in internships and academic projects.

  Experience Highlights:
  - Developed a Diabetic Retinopathy Detection System: Achieved over 90% accuracy in detecting leaks in retinal angiographs using custom-designed CNNs.
  - Automated Medical/Research Document Classification: Built ML models (K-Means, Random Forest, XGBoost) to automate document classification for The Digital Group, achieving an 85% accuracy on 1 million+ documents.
  - Enhanced Code Classification with NLP: Improved code classification accuracy to 98% by training NLP models and optimizing vectorization techniques (Word2Vec, Doc2Vec).
      
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diabetic Retinopathy Detection using Retinal Angiogram
        link: https://github.com/kartikeyavi/Diabatic-Retinopathy
        link_text: Github Repository
        icon: fab fa-github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/kartikeyavi/resume
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Developed a high-accuracy diabetic retinopathy detection system using Machine Learning
            - Built a scalable Machine Learning pipeline in Python to process over 100GB of retinal angiogram scans for diabetic retinopathy (DR) detection, a leading cause of blindness globally.
            - Implemented and compared various image pre-processing techniques (filters, cropping, normalization) to optimize Convolutional Neural Network (CNN) input for superior performance.
            - Designed and trained a CNN model achieving >90% accuracy in DR detection using TensorFlow, NumPy, OpenCV, and scikit-learn libraries.
            - Experimented with diverse CNN architectures (convolutional, pooling, dense layers) and activation functions (ReLU, tanh, sigmoid) to achieve optimal results.
      - layout: left
        title: Hermes News Feed
        link: https://github.com/kartikeyavi/Hermes-News-Feed
        link_text: Github Repository
        icon: fab fa-github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/kartikeyavi/resume
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Developed a daily news aggregator using Python and modern web technologies.
            - Automated news scraping: Built a Python script utilizing Selenium to gather daily news articles from various sources, covering diverse topics.
            - Data pipeline and API development: Implemented a Flask application to ingest scraped articles, store them in an SQL database, and provide an API for access.
            - Search functionality: Enhanced the API to return search results based on user queries.
            - NLP-powered article analysis: Leveraged Natural Language Processing (NLP) techniques to automatically tag scraped articles for improved organization.
            - Team leadership: Led the development of a user-friendly frontend using HTML, CSS, JavaScript, and React, showcasing the API's functionalities.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: kartikeyavi/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
