# Site
repository: kartikeyavi/modern-resume-theme
favicon: images/favicon.ico


# Content configuration version
version: 2

# Personal info
name:  KARTIKEYA SINGH
title: Machine Learning Developer
email: kartikeyavia2r@gmail.com  
phone: +91-7339910494

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  kartikeyavi
linkedin_username: kartikeyavi


# About Section
# about_title: About Me
about_profile_image: images/Profile Picture.jpg
about_content: | # this will include new lines to allow paragraphs
  Fueled by a lifelong fascination with data and a knack for untangling complex equations, I'm Kartikeya Singh, a Machine Learning researcher with a passion for innovation. I've been fascinated by the world of data and equations, since I could remember. When I discovered Machine Learning (ML), it was a revelation. It allowed me to bridge the gap between my analytical instincts and real-world applications. 

  My passion for ML led me on a journey of exploration. I honed my skills at CyberPWN, building models to detect and categorize malware. At CDAC, I honed my skills in computer vision and explored various projects, further deepening my understanding of machine learning.  My most recent role at the Digital Group allowed me to delve into the fascinating world of natural language processing (NLP). This diverse exposure has equipped me with a well-rounded skillset across multiple ML domains.

  However, my true calling lies in research. I thrive on the constant quest for innovation. My greatest joy comes from uncovering new ideas and applying them to solve problems in creative ways. Conferences further ignited my love for academia, and I'm currently delving into the world of ML research. I'm meticulously studying algorithms through their mathematical foundations and original research papers.

  My Research Interests include:

  - Machine Learning
  - Computer Vision
  - Natural Language Processing

  Driven by a deep desire to push the boundaries of ML innovation, I am actively pursuing a research career.  The opportunity to delve deeper into the theoretical underpinnings of Machine Learning algorithms through in-depth study of original research papers excites me immensely.  I am confident that my strong analytical skills and experience in applying various ML techniques will allow me to thrive in a research setting.

  Let's connect! Feel free to reach out using the email address or phone number provided in the header.



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diabetic Retinopathy Detection using Retinal Angiogram
        link: https://github.com/kartikeyavi/Diabatic-Retinopathy
        link_text: Github Repository
        icon: fab fa-github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/kartikeyavi/resume
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Developed a high-accuracy diabetic retinopathy detection system using Machine Learning
            - Built a scalable Machine Learning pipeline in Python to process over 100GB of retinal angiogram scans for diabetic retinopathy (DR) detection, a leading cause of blindness globally.
            - Implemented and compared various image pre-processing techniques (filters, cropping, normalization) to optimize Convolutional Neural Network (CNN) input for superior performance.
            - Designed and trained a CNN model achieving >90% accuracy in DR detection using TensorFlow, NumPy, OpenCV, and scikit-learn libraries.
            - Experimented with diverse CNN architectures (convolutional, pooling, dense layers) and activation functions (ReLU, tanh, sigmoid) to achieve optimal results.
      - layout: left
        title: Hermes News Feed
        link: https://github.com/kartikeyavi/Hermes-News-Feed
        link_text: Github Repository
        icon: fab fa-github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/kartikeyavi/resume
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Developed a daily news aggregator using Python and modern web technologies.
            - Automated news scraping: Built a Python script utilizing Selenium to gather daily news articles from various sources, covering diverse topics.
            - Data pipeline and API development: Implemented a Flask application to ingest scraped articles, store them in an SQL database, and provide an API for access.
            - Search functionality: Enhanced the API to return search results based on user queries.
            - NLP-powered article analysis: Leveraged Natural Language Processing (NLP) techniques to automatically tag scraped articles for improved organization.
            - Team leadership: Led the development of a user-friendly frontend using HTML, CSS, JavaScript, and React, showcasing the API's functionalities.
  
  - title: Keyskills # Title for the section
    layout: text # Type of content section (list/text)
    content:
      description: 
        - Progamming Language Skills
          - Python

          - R
          | - Java (Basic)
            - C/C++ (Basic)



  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Digital Group
        link: https://www.thedigitalgroup.com/
        # link_text: boringcompany.com
        sub_title: Software Trainee
        caption: October 2023 - March 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Leveraged machine learning algorithms like K-Means, BIRCH, and DBSCAN to achieve an accuracy of 85% in document clustering. This intelligent grouping of similar documents facilitated faster information retrieval and analysis by researchers.
          - To address the complexities of medical/research code, I constructed and trained robust Natural Language Processing (NLP) models using Random Forest and XGBoost algorithms. These models achieved a remarkable accuracy of 98% on a massive dataset of over 150,000 code lines, significantly streamlining the analysis process for researchers.
          - Furthermore, I meticulously optimized vectorization models like Word2Vec and Doc2Vec, resulting in a 20-30% improvement in model efficiency. This translates to reduced processing time and lower resource consumption, making the system more scalable and cost-effective.
 
      - layout: left
        title: CyberPWN Technologies
        link: https://www.cyberpwn.com/
        # link_text: boringcompany.com
        sub_title: Data Science Intern
        caption: February 2022 - March 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          At the cutting edge of cybersecurity, I played a pivotal role in integrating machine learning to bolster network defenses. My focus areas included:
          - Automated Anomaly Detection: I spearheaded the implementation of machine learning algorithms to continuously analyze network activity. This included traffic patterns, user behavior, and IP data. By establishing baselines for normal activity, the algorithms could identify deviations in real-time, allowing for swift intervention and potential breach prevention.
          - Data-Driven Threat Classification: Leveraging statistical modeling techniques, I developed a system for clustering and classifying network breaches. This system categorized security incidents based on their characteristics, enabling faster prioritization and response. This not only streamlined the security team's workflow but also minimized potential damage from lingering threats.
   
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Center for Development of Advanced Computing, Pune
        sub_title: Post Graduate - Diploma in Big Data Analytics
        caption: March 2023 - September 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Graduated with a Distinction (73.89%) in a rigorous PG Diploma program focusing on Machine Learning, Natural Language Processing, Data Science, and Artificial Intelligence.
          - Demonstrated a passion for independent learning by actively exploring Computer Vision and related topics beyond the curriculum.
          - Sought out mentorship by consistently engaging with instructors with over 28 years of experience, further deepening my understanding of various topics. This proactive approach was the most rewarding aspect of my program and ignited my interest in a research-oriented career.
          - Exceeded expectations by completing advanced final projects that went beyond the scope of the syllabus, showcasing my ability to tackle complex problems independently.


      - layout: left
        title: KIIT University
        sub_title: B. Tech in Information Technology
        caption: October 2019 - May 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Graduated with a strong GPA of 8.04, demonstrating proficiency in a rigorous engineering curriculum.
          - Equipped myself with in-demand technical skills through coursework in Machine Learning, Natural Language Processing (NLP), Data Science, and Artificial Intelligence (AI).
          - Completed diverse final-year projects, showcasing my ability to apply knowledge across various domains, including Web Development and Artificial Intelligence.
      - layout: left
        title: High School Education
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Secured a commendable 79.8% in the Class 12th CBSE Board Examinations (2019) at Delhi Public School, Jodhpur.
          - Achieved a strong 79.6% in the Class 10th CBSE Board Examinations (2017) at Delhi Public School, Jodhpur.
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: kartikeyavi/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
